# --- Team1 private DNS ---
listen-address=10.7.26.16,127.0.0.1
bind-interfaces
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=1.1.1.1

# project records (both point to the edge, Mac2)
address=/app.team1.test/10.7.31.188
address=/api.team1.test/10.7.31.188

# short TTL, needed for Extension B
local-ttl=30

# logging (useful evidence)
log-queries
log-facility=/tmp/dnsmasq.log
